import {
  User,
  Post,
  Conversation,
  NotificationItem,
  GroupItem,
  PageItem,
  SavedCollection,
  TrendingTopic,
  ActiveSession,
} from '../types';

export const CURRENT_USER: User = {
  id: 'user_shivam_01',
  name: 'Shivam Kumar',
  username: 'shivam_dev',
  avatar: '/src/assets/images/avatar_shivam_1790446497274.jpg',
  coverImage: '/src/assets/images/group_banner_dev_1790446548511.jpg',
  headline: 'Java Backend Developer · Spring Boot | Java | PostgreSQL',
  bio: 'Passionate software engineer building resilient microservices, high-throughput distributed systems, and clean domain architectures. Avid coffee brewer and open-source contributor.',
  location: 'Bengaluru, India',
  website: 'https://github.com/shivam-dev',
  joinedDate: 'March 2024',
  isVerified: true,
  followersCount: 1420,
  followingCount: 384,
  postsCount: 47,
  work: 'Senior Backend Engineer @ CloudScale Tech',
  education: 'B.Tech in Computer Science',
  interests: ['Spring Boot', 'Java 21', 'PostgreSQL', 'Microservices', 'System Design', 'Redis', 'Kafka'],
  isFollowing: false,
};

export const INITIAL_FRIENDS: User[] = [
  {
    id: 'user_priya_02',
    name: 'Priya Sharma',
    username: 'priya_design',
    avatar: '/src/assets/images/avatar_designer_1790446517358.jpg',
    headline: 'Lead Product Designer @ Finova · Design Systems & UX',
    bio: 'Crafting minimalist, intuitive interfaces and scalable design tokens. Speaker & mentor.',
    location: 'Mumbai, India',
    isVerified: true,
    followersCount: 3200,
    followingCount: 410,
    postsCount: 92,
    mutualFriends: 18,
    isFollowing: true,
    distanceKm: 4.8,
  },
  {
    id: 'user_alex_03',
    name: 'Alex Chen',
    username: 'alexchen_arch',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    headline: 'Cloud Solutions Architect · AWS / Kubernetes / Rust',
    bio: 'Distributed systems fanatic. Turning legacy monoliths into lightweight event-driven clouds.',
    location: 'Singapore',
    isVerified: true,
    followersCount: 2840,
    followingCount: 312,
    postsCount: 64,
    mutualFriends: 14,
    isFollowing: true,
    distanceKm: 12.0,
  },
  {
    id: 'user_marcus_04',
    name: 'Marcus Vance',
    username: 'marcus_v',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    headline: 'Engineering Manager @ DevCore',
    bio: 'Empowering engineering teams to ship high-impact products with velocity and empathy.',
    location: 'Berlin, Germany',
    isVerified: false,
    followersCount: 1980,
    followingCount: 520,
    postsCount: 38,
    mutualFriends: 7,
    isFollowing: true,
    distanceKm: 28.5,
  },
  {
    id: 'user_maya_05',
    name: 'Maya Lin',
    username: 'maya_ai',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    headline: 'Machine Learning Researcher · NLP & Vector Retrieval',
    bio: 'Exploring sparse attention mechanisms and multimodal embedding pipelines.',
    location: 'San Francisco, CA',
    isVerified: true,
    followersCount: 5400,
    followingCount: 620,
    postsCount: 110,
    mutualFriends: 22,
    isFollowing: false,
    distanceKm: 18.2,
  },
];

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post_01',
    author: {
      id: 'user_shivam_01',
      name: 'Shivam Kumar',
      username: 'shivam_dev',
      avatar: '/src/assets/images/avatar_shivam_1790446497274.jpg',
      isVerified: true,
    },
    content:
      'Refactored our connection pool in Spring Boot 3.3 today with HikariCP optimizations. By tuning `maximumPoolSize` to match our PostgreSQL CPU cores + spindle count formula, we dropped p99 query latency from 84ms down to 11ms under 15k concurrent requests! 🚀\n\nAlways measure before making assumptions about database bottlenecking.',
    timestamp: '2 hours ago',
    privacy: 'public',
    hashtags: ['SpringBoot', 'Java', 'PostgreSQL', 'SystemDesign'],
    mediaUrl: '/src/assets/images/post_photo_tech_1790446531677.jpg',
    mediaType: 'image',
    likesCount: 148,
    commentsCount: 23,
    sharesCount: 19,
    isLiked: false,
    isSaved: true,
    location: 'Bengaluru Tech Park',
    comments: [
      {
        id: 'c_01',
        author: {
          id: 'user_alex_03',
          name: 'Alex Chen',
          username: 'alexchen_arch',
          avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
        },
        content: 'Impressive drop! Did you also tweak the idleTimeout and connectionTimeout thresholds?',
        timestamp: '1 hour ago',
        likesCount: 7,
      },
      {
        id: 'c_02',
        author: {
          id: 'user_shivam_01',
          name: 'Shivam Kumar',
          username: 'shivam_dev',
          avatar: '/src/assets/images/avatar_shivam_1790446497274.jpg',
        },
        content: 'Yes! Set connectionTimeout to 3000ms to fail-fast under surge traffic rather than stacking queued worker threads.',
        timestamp: '45 mins ago',
        likesCount: 4,
      },
    ],
  },
  {
    id: 'post_02',
    author: {
      id: 'user_priya_02',
      name: 'Priya Sharma',
      username: 'priya_design',
      avatar: '/src/assets/images/avatar_designer_1790446517358.jpg',
      isVerified: true,
    },
    content:
      'The best user interfaces do not shout for attention. They anticipate what you need next, preserve visual rhythm, and respect user focus.\n\nHere are 3 rules we applied when redesigning our core workflow:\n1. Zero redundant border boxes — let generous whitespace breathe.\n2. Monospace tabular numerals for all telemetry data.\n3. Micro-interactions limited to strictly under 200ms.',
    timestamp: '5 hours ago',
    privacy: 'public',
    hashtags: ['UIUX', 'DesignSystems', 'ProductDesign', 'Frontend'],
    likesCount: 289,
    commentsCount: 31,
    sharesCount: 45,
    isLiked: true,
    isSaved: false,
    comments: [
      {
        id: 'c_03',
        author: {
          id: 'user_marcus_04',
          name: 'Marcus Vance',
          username: 'marcus_v',
          avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
        },
        content: 'Sub-200ms latency is non-negotiable. Users immediately feel the cognitive drag otherwise.',
        timestamp: '3 hours ago',
        likesCount: 12,
      },
    ],
  },
  {
    id: 'post_03',
    author: {
      id: 'user_maya_05',
      name: 'Maya Lin',
      username: 'maya_ai',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
      isVerified: true,
    },
    content:
      'Excited to announce our open paper on hybrid semantic search! Combining dense vectors with BM25 keyword matching gives superior recall for specialized engineering queries where exact keywords matter as much as context.\n\nCheck out the benchmark repository and let us know your thoughts.',
    timestamp: 'Yesterday',
    privacy: 'public',
    hashtags: ['MachineLearning', 'Search', 'VectorDB', 'OpenSource'],
    mediaUrl: '/src/assets/images/hero_social_preview_1790446483047.jpg',
    mediaType: 'image',
    likesCount: 412,
    commentsCount: 58,
    sharesCount: 77,
    isLiked: false,
    isSaved: true,
    comments: [],
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_priya',
    participant: {
      id: 'user_priya_02',
      name: 'Priya Sharma',
      username: 'priya_design',
      avatar: '/src/assets/images/avatar_designer_1790446517358.jpg',
      isOnline: true,
    },
    lastMessage: 'The new token spec looks great. I just updated the Figma variables.',
    timestamp: '12m ago',
    unreadCount: 1,
    messages: [
      {
        id: 'm1',
        senderId: 'user_priya_02',
        text: 'Hey Shivam! Did you see the updated dashboard mockups?',
        timestamp: '10:30 AM',
        status: 'read',
      },
      {
        id: 'm2',
        senderId: 'user_shivam_01',
        text: 'Yes! Loved the clean spacing and dark mode contrast balance. Super readable.',
        timestamp: '10:35 AM',
        status: 'read',
      },
      {
        id: 'm3',
        senderId: 'user_priya_02',
        text: 'The new token spec looks great. I just updated the Figma variables.',
        timestamp: '10:42 AM',
        status: 'delivered',
      },
    ],
  },
  {
    id: 'conv_alex',
    participant: {
      id: 'user_alex_03',
      name: 'Alex Chen',
      username: 'alexchen_arch',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      isOnline: false,
      lastSeen: '1 hour ago',
    },
    lastMessage: 'Are we still on for the system design review tomorrow at 3 PM?',
    timestamp: '2h ago',
    unreadCount: 0,
    messages: [
      {
        id: 'm4',
        senderId: 'user_alex_03',
        text: 'Are we still on for the system design review tomorrow at 3 PM?',
        timestamp: '09:15 AM',
        status: 'read',
      },
    ],
  },
  {
    id: 'conv_marcus',
    participant: {
      id: 'user_marcus_04',
      name: 'Marcus Vance',
      username: 'marcus_v',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      isOnline: true,
    },
    lastMessage: 'Thanks for sending over the HikariCP metrics summary!',
    timestamp: 'Yesterday',
    unreadCount: 0,
    messages: [
      {
        id: 'm5',
        senderId: 'user_marcus_04',
        text: 'Thanks for sending over the HikariCP metrics summary!',
        timestamp: 'Yesterday',
        status: 'read',
      },
    ],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    type: 'like',
    actor: {
      id: 'user_priya_02',
      name: 'Priya Sharma',
      username: 'priya_design',
      avatar: '/src/assets/images/avatar_designer_1790446517358.jpg',
    },
    targetTitle: 'HikariCP optimizations post',
    timestamp: '15m ago',
    isRead: false,
  },
  {
    id: 'notif_02',
    type: 'comment',
    actor: {
      id: 'user_alex_03',
      name: 'Alex Chen',
      username: 'alexchen_arch',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
    targetTitle: 'HikariCP optimizations post',
    timestamp: '1h ago',
    isRead: false,
  },
  {
    id: 'notif_03',
    type: 'follow',
    actor: {
      id: 'user_maya_05',
      name: 'Maya Lin',
      username: 'maya_ai',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
    timestamp: '3h ago',
    isRead: true,
  },
  {
    id: 'notif_04',
    type: 'group',
    actor: {
      id: 'group_spring_hub',
      name: 'Spring Boot Architects',
      username: 'springboot_arch',
      avatar: '/src/assets/images/group_banner_dev_1790446548511.jpg',
    },
    targetTitle: 'invited you to join the monthly discussion',
    timestamp: '1d ago',
    isRead: true,
  },
  {
    id: 'notif_05',
    type: 'system',
    actor: {
      id: 'nexora_system',
      name: 'NEXORA Security',
      username: 'nexora_sec',
      avatar: '/src/assets/images/avatar_shivam_1790446497274.jpg',
    },
    targetTitle: 'New login detected from Chrome on macOS in Bengaluru',
    timestamp: '2d ago',
    isRead: true,
  },
];

export const INITIAL_GROUPS: GroupItem[] = [
  {
    id: 'grp_01',
    name: 'Spring Boot Architects',
    description: 'Community for Java, Spring Framework, and reactive microservices practitioners.',
    avatar: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=150&auto=format&fit=crop&q=80',
    coverImage: '/src/assets/images/group_banner_dev_1790446548511.jpg',
    membersCount: 14200,
    privacy: 'Public',
    category: 'Engineering',
    isJoined: true,
  },
  {
    id: 'grp_02',
    name: 'Distributed Systems & Cloud',
    description: 'Deep dives into consensus protocols, Raft, Paxos, Kafka, and cloud infrastructure.',
    avatar: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=150&auto=format&fit=crop&q=80',
    coverImage: '/src/assets/images/hero_social_preview_1790446483047.jpg',
    membersCount: 9850,
    privacy: 'Public',
    category: 'Architecture',
    isJoined: true,
  },
  {
    id: 'grp_03',
    name: 'Design Systems Guild',
    description: 'Cross-functional designers and frontend engineers crafting cohesive component libraries.',
    avatar: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=150&auto=format&fit=crop&q=80',
    coverImage: '/src/assets/images/post_photo_tech_1790446531677.jpg',
    membersCount: 7300,
    privacy: 'Public',
    category: 'Design',
    isJoined: false,
  },
  {
    id: 'grp_04',
    name: 'PostgreSQL Performance & DBA',
    description: 'Index tuning, query plans, vacuuming, and high-availability PostgreSQL clusters.',
    avatar: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=150&auto=format&fit=crop&q=80',
    coverImage: '/src/assets/images/group_banner_dev_1790446548511.jpg',
    membersCount: 5410,
    privacy: 'Private',
    category: 'Databases',
    isJoined: false,
  },
];

export const INITIAL_PAGES: PageItem[] = [
  {
    id: 'page_01',
    name: 'DevCore Engineering',
    description: 'Insights, engineering blogs, and infrastructure releases from DevCore Labs.',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    coverImage: '/src/assets/images/group_banner_dev_1790446548511.jpg',
    category: 'Technology Company',
    followersCount: 48900,
    isFollowing: true,
  },
  {
    id: 'page_02',
    name: 'The Modern Backend',
    description: 'Curated articles on microservices, event-sourcing, and distributed database designs.',
    logo: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=150&auto=format&fit=crop&q=80',
    category: 'Media / Publication',
    followersCount: 22100,
    isFollowing: true,
  },
  {
    id: 'page_03',
    name: 'UI Craftsman',
    description: 'Showcasing extraordinary interface craftsmanship, interactions, and design systems.',
    logo: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80',
    category: 'Design Agency',
    followersCount: 31400,
    isFollowing: false,
  },
];

export const INITIAL_COLLECTIONS: SavedCollection[] = [
  {
    id: 'col_01',
    name: 'Java & Spring Resources',
    description: 'Curated deep-dives on concurrency, virtual threads, and HikariCP connection tuning.',
    privacy: 'Public',
    postIds: ['post_01'],
    updatedAt: 'Today',
  },
  {
    id: 'col_02',
    name: 'Design Systems & UX Tokens',
    description: 'Interface principles, typography scales, and accessible micro-interaction patterns.',
    privacy: 'Private',
    postIds: ['post_02'],
    updatedAt: '2 days ago',
  },
  {
    id: 'col_03',
    name: 'AI & Vector Retrieval Papers',
    description: 'Research papers, sparse-dense hybrid architectures, and RAG optimization.',
    privacy: 'Public',
    postIds: ['post_03'],
    updatedAt: 'Last week',
  },
];

export const TRENDING_TOPICS: TrendingTopic[] = [
  { id: 'tr_1', hashtag: 'SpringBoot33', category: 'Backend Engineering', postsCount: '18.4K posts' },
  { id: 'tr_2', hashtag: 'Java21VirtualThreads', category: 'Technology', postsCount: '14.2K posts' },
  { id: 'tr_3', hashtag: 'DesignSystems', category: 'Design', postsCount: '9.8K posts' },
  { id: 'tr_4', hashtag: 'PostgreSQL17', category: 'Databases', postsCount: '8.1K posts' },
  { id: 'tr_5', hashtag: 'SystemDesign', category: 'Architecture', postsCount: '24.6K posts' },
];

export const ACTIVE_SESSIONS: ActiveSession[] = [
  {
    id: 'sess_01',
    device: 'MacBook Pro 16"',
    browser: 'Chrome 128.0',
    location: 'Bengaluru, India',
    lastActive: 'Active now',
    isCurrent: true,
  },
  {
    id: 'sess_02',
    device: 'Google Pixel 8 Pro',
    browser: 'Android App / Mobile Web',
    location: 'Bengaluru, India',
    lastActive: '45 mins ago',
    isCurrent: false,
  },
  {
    id: 'sess_03',
    device: 'Windows Workstation',
    browser: 'Edge 126.0',
    location: 'Bengaluru, India',
    lastActive: '2 days ago',
    isCurrent: false,
  },
];
