spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: 1000ms
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

nexora:
  otp:
    dev-mode-echo-console: false

logging:
  level:
    root: WARN
    com.nexora: INFO
    org.springframework.security: WARN
